[package]
name = "doc_db"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
tower = "0.4.13"
axum = "0.7.5"
reqwest = { version = "0.12", features = ["json"] }